---
# Main tasks for service monitoring using direct SSH commands

- name: Ensure log directory exists
  ansible.builtin.raw: |
    [ -d "{{ aix_log_dir }}" ] || mkdir -p "{{ aix_log_dir }}"
    chmod 755 "{{ aix_log_dir }}"
  changed_when: false
  tags:
    - service_monitoring
    - setup

- name: Ensure script directory exists
  ansible.builtin.raw: |
    [ -d "{{ aix_script_dir }}" ] || mkdir -p "{{ aix_script_dir }}"
    chmod 755 "{{ aix_script_dir }}"
  changed_when: false
  tags:
    - service_monitoring
    - setup

- name: Check for high load indicators
  ansible.builtin.raw: |
    HIGH_LOAD_INDICATOR="zabbix_agentd"
    
    # Check for high load indicators related to monitored services
    if ps aux | head | grep -q "$HIGH_LOAD_INDICATOR"; then
      echo "HIGH_LOAD_DETECTED=YES"
      ps aux | head | grep "$HIGH_LOAD_INDICATOR" | grep -v grep
    else
      echo "HIGH_LOAD_DETECTED=NO"
    fi
  register: high_load_check
  changed_when: false
  tags:
    - service_monitoring
    - zabbix

- name: Initialize service monitoring log
  ansible.builtin.raw: |
    LOG_FILE="/bigc/log/service_monitoring_$(hostname)_$(date +%Y%m%d).log"
    
    echo "=============================== SERVICE MONITORING ===============================" > "$LOG_FILE"
    echo "Date: $(date)" >> "$LOG_FILE"
    echo "Hostname: $(hostname)" >> "$LOG_FILE"
    echo "Change Ticket: AUTO" >> "$LOG_FILE"
    echo "Change Reason: Automated service monitoring via AAP" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    echo "High load check for zabbix_agentd:" >> "$LOG_FILE"
    # Check current load status
    if ps aux | head | grep -q "zabbix_agentd"; then
      echo "HIGH_LOAD_DETECTED=YES" >> "$LOG_FILE"
    else
      echo "HIGH_LOAD_DETECTED=NO" >> "$LOG_FILE"
    fi
    echo "" >> "$LOG_FILE"
  register: service_log_init
  changed_when: false
  tags:
    - service_monitoring
    - logging

- name: Restart Zabbix agent if high load detected
  ansible.builtin.raw: |
    LOG_FILE="/bigc/log/service_monitoring_$(hostname)_$(date +%Y%m%d).log"
    RESTART_SCRIPT="/bigc/script/zabbix_restart.sh"
    SERVICE_NAME="zabbix_agentd"
    RESTART_WAIT="10"
    SERVICE_RESTARTED=NO
    
    # Check if high load was detected
    if ps aux | head | grep -q "zabbix_agentd"; then
      echo "High load detected - would restart Zabbix agent" >> "$LOG_FILE"
      echo "" >> "$LOG_FILE"
      echo "Process status before restart:" >> "$LOG_FILE"
      ps -ef | grep "$SERVICE_NAME" | grep -v grep >> "$LOG_FILE" || echo "No $SERVICE_NAME processes found" >> "$LOG_FILE"
      echo "" >> "$LOG_FILE"
      
      # Simulate service restart for validation
      echo "[SIMULATION] Would create and execute Zabbix restart script" >> "$LOG_FILE"
      echo "[SIMULATION] Script location: $RESTART_SCRIPT" >> "$LOG_FILE"
      echo "[SIMULATION] Service restart completed successfully" >> "$LOG_FILE"
      
      # Wait for simulation
      sleep 3
      
      # Check process status after simulation
      echo "" >> "$LOG_FILE"
      echo "Show current zabbix agent process:" >> "$LOG_FILE"
      ps -ef | grep "$SERVICE_NAME" | grep -v grep >> "$LOG_FILE" || echo "No $SERVICE_NAME processes found" >> "$LOG_FILE"
      echo "" >> "$LOG_FILE"
      echo "Recommended Action: This is a validation run - no actual restart performed" >> "$LOG_FILE"
      echo "" >> "$LOG_FILE"
      echo "---------------------- By EIS Command Center ----------------------" >> "$LOG_FILE"
      
      SERVICE_RESTARTED=SIMULATED
    else
      echo "No high load detected for $SERVICE_NAME - no action needed" >> "$LOG_FILE"
    fi
    
    echo "SERVICE_RESTARTED=$SERVICE_RESTARTED"
  register: service_restart
  changed_when: false
  failed_when: false
  tags:
    - service_monitoring
    - zabbix

- name: Send email notification if service was restarted
  ansible.builtin.raw: |
    echo "Email notification skipped - validation mode"
  when: false
  failed_when: false
  tags:
    - service_monitoring
    - notification

- name: Display service monitoring results
  ansible.builtin.raw: |
    echo "====================================="
    echo "Service monitoring completed on $(hostname)"
    if ps aux | head | grep -q "zabbix_agentd"; then
      echo "High load detected: YES"
    else
      echo "High load detected: NO"
    fi
    echo "Log file: /bigc/log/service_monitoring_$(hostname)_$(date +%Y%m%d).log"
    echo "====================================="
  tags:
    - service_monitoring
    - results