---
# Playbook: Authenticate to Cloud Provider
# Modular, supports AWS, Azure, GCP via survey
- name: Authenticate to Cloud Provider
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../surveys/cloud-auth-survey.json
  roles:
    - role: cloud_auth
      vars:
        # cloud_provider, credentials, cloud_auth_file, vault_password_file
  tasks:
    - name: Save survey answers to prefilled vars file if requested
      when: save_prefilled_vars is defined and save_prefilled_vars == 'yes'
      copy:
        content: "{{ vars | to_nice_yaml }}"
        dest: "{{ prefilled_vars_file_name | default('prefilled-survey-vars.yml') }}"
