---
# Playbook: Provision Cloud Server
#
# This playbook provisions a cloud server and its associated resources.
# It is designed for use with the Ansible Automation Platform 2.5 web console.
#
- name: Provision Cloud Server
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    # These variables are expected to be provided by the AAP survey
    cloud_provider: "{{ cloud_provider | default('aws') }}"
    resource_group: "{{ resource_group | default('default') }}"
    location: "{{ location | default('us-east-1') }}"
    server_name: "{{ server_name | default('my-server') }}"
    instance_type: "{{ instance_type | default('t2.micro') }}"
    image: "{{ image | default('ami-0c55b159cbfafe1f0') }}" # Default to Amazon Linux 2

  tasks:
    - name: Include cloud-specific provisioning tasks
      include_role:
        name: "cloud_server_{{ cloud_provider }}"