---
# Playbook: Query Unused Cloud Resources
# Modular, supports AWS, Azure, GCP via survey
- name: Query Unused Cloud Resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../surveys/query-unused-resources-survey.json
    - ../prefilled-survey-vars.yml
    - ../cloud_auth.yml
  pre_tasks:
    - name: Check if prefilled vars file exists
      stat:
        path: ../prefilled-survey-vars.yml
      register: prefilled_vars_file
    - name: Include prefilled vars if file exists and user selected it
      include_vars:
        file: ../prefilled-survey-vars.yml
      when: prefilled_vars_file.stat.exists and (survey_mode is defined and survey_mode == 'Use prefilled vars file if available')
    - name: Include cloud authentication vars if available
      include_vars:
        file: ../cloud_auth.yml
      ignore_errors: yes
  roles:
    - role: cloud_query_unused
      vars:
        # cloud_provider, region, resource_group, gcp_project, unused_resource_output_file
  tasks:
    - name: Save survey answers to prefilled vars file if requested
      when: save_prefilled_vars is defined and save_prefilled_vars == 'yes' and (survey_mode is not defined or survey_mode == 'Prompt me every time (survey)')
      copy:
        content: "{{ vars | to_nice_yaml }}"
        dest: "{{ prefilled_vars_file_name | default('prefilled-survey-vars.yml') }}"
