---
# Enable HTTPS API Access on FortiGate
# Run this once to enable API access for Ansible automation

- name: Enable FortiGate HTTPS API Access
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: network_cli
  become: no
  vars:
    ansible_network_os: fortinet.fortios.fortios
    ansible_port: 22
    
  tasks:
    - name: Enable HTTPS admin access
      fortinet.fortios.fortios_command:
        commands:
          - config system global
          - set admin-sport 443
          - set admin-https-redirect enable
          - end
      register: enable_https
      
    - name: Save configuration
      fortinet.fortios.fortios_command:
        commands:
          - execute backup config flash
      register: save_config
      
    - name: Show configuration result
      debug:
        msg:
          - "HTTPS API Configuration:"
          - "HTTPS Admin Port: Enabled on 443"
          - "HTTPS Redirect: Enabled"
          - "Config saved: {{ 'Yes' if save_config is succeeded else 'Failed' }}"
          - ""
          - "✅ API access should now be available on port 443"
          - ""
          - "Next steps:"
          - "1. Update AAP inventory to use httpapi connection"
          - "2. Change ansible_port from 22 to 443"
          - "3. Test with your original playbooks"