---
# Execution Environment for AAP 2.5 Fortinet Management
# This EE includes all necessary collections and dependencies for Fortinet operations

version: 3

images:
  base_image:
    name: 'quay.io/ansible/automation-hub-ee:latest'

dependencies:
  system: bindep.txt
  python: requirements.txt
  ansible: requirements.yml

additional_build_steps:
  prepend_base:
    - RUN whoami
    - RUN cat /etc/os-release
  prepend_galaxy:
    - RUN ansible-galaxy collection install --force fortinet.fortios
    - RUN ansible-galaxy collection install --force community.general
    - RUN ansible-galaxy collection install --force ansible.posix
    - RUN ansible-galaxy collection install --force ansible.netcommon
  prepend_final:
    - RUN ls -la /usr/share/ansible/collections/
    - RUN pip list | grep -E "(ansible|requests|urllib3)"

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"
