---
# Main tasks for print queue management using direct SSH commands

- name: Ensure log directory exists
  ansible.builtin.raw: |
    [ -d "{{ aix_log_dir }}" ] || mkdir -p "{{ aix_log_dir }}"
    chmod 755 "{{ aix_log_dir }}"
  changed_when: false
  tags:
    - print_queue
    - setup

- name: Check spooler service group status
  ansible.builtin.raw: |
    # Check if spooler service group has inoperative services
    if lssrc -g spooler 2>/dev/null | grep -q inoperative; then
      echo "SPOOLER_INOPERATIVE=YES"
      lssrc -g spooler
    else
      echo "SPOOLER_INOPERATIVE=NO"
    fi
  register: spooler_check
  changed_when: false
  tags:
    - print_queue
    - spooler

- name: Initialize print queue monitoring log
  ansible.builtin.raw: |
    LOG_FILE="/bigc/log/print_queue_$(hostname)_$(date +%Y%m%d).log"
    SPOOLER_LOG="/bigc/log/spooler_$(hostname)_$(date +%Y%m%d).log"
    
    echo "=============================== PRINT QUEUE MONITORING ===============================" > "$LOG_FILE"
    echo "Date: $(date)" >> "$LOG_FILE"
    echo "Hostname: $(hostname)" >> "$LOG_FILE"
    echo "Change Ticket: AUTO" >> "$LOG_FILE"
    echo "Change Reason: Automated print queue management via AAP" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    echo "Current print queue status:" >> "$LOG_FILE"
    lpstat -a >> "$LOG_FILE" 2>/dev/null || echo "No print queues found" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
  register: print_queue_log_init
  changed_when: false
  tags:
    - print_queue
    - logging

- name: Restart spooler service group if inoperative
  ansible.builtin.raw: |
    SPOOLER_LOG="/bigc/log/spooler_$(hostname)_$(date +%Y%m%d).log"
    SPOOLER_RESTARTED=NO
    
    # Check if spooler was found inoperative
    if lssrc -g spooler 2>/dev/null | grep -q inoperative; then
      echo "=============================== SPOOLER SERVICE RESTART ===============================" > "$SPOOLER_LOG"
      echo "Date: $(date)" >> "$SPOOLER_LOG"
      echo "Hostname: $(hostname)" >> "$SPOOLER_LOG"
      echo "Change Ticket: AUTO" >> "$SPOOLER_LOG"
      echo "Change Reason: Automated spooler restart via AAP" >> "$SPOOLER_LOG"
      echo "" >> "$SPOOLER_LOG"
      
      echo "Spooler status before restart:" >> "$SPOOLER_LOG"
      lssrc -g spooler >> "$SPOOLER_LOG" 2>/dev/null
      echo "" >> "$SPOOLER_LOG"
      
      # Restart spooler service group
      echo "Restarting spooler service group..." >> "$SPOOLER_LOG"
      if startsrc -g spooler >> "$SPOOLER_LOG" 2>&1; then
        echo "Spooler restart command executed" >> "$SPOOLER_LOG"
        
        # Wait for restart
        sleep 10
        
        # Check post-restart status
        echo "$(date)" >> "$SPOOLER_LOG"
        echo "Spooler status after restart:" >> "$SPOOLER_LOG"
        lssrc -g spooler >> "$SPOOLER_LOG" 2>/dev/null
        echo "" >> "$SPOOLER_LOG"
        echo "Recommended Action: If status: running, No response action is required." >> "$SPOOLER_LOG"
        echo "Recommended Action: If status: inoperative, Please call to EIS Unix-Linux Admin Team for review" >> "$SPOOLER_LOG"
        echo "" >> "$SPOOLER_LOG"
        echo "---------------------- By EIS Command Center ----------------------" >> "$SPOOLER_LOG"
        
        SPOOLER_RESTARTED=YES
      else
        echo "Failed to restart spooler service group" >> "$SPOOLER_LOG"
        echo "---------------------- By EIS Command Center ----------------------" >> "$SPOOLER_LOG"
      fi
    fi
    
    echo "SPOOLER_RESTARTED=$SPOOLER_RESTARTED"
  register: spooler_restart
  changed_when: "'SPOOLER_RESTARTED=YES' in spooler_restart.stdout"
  failed_when: false
  tags:
    - print_queue
    - spooler

- name: Check individual print queue status and restart if needed
  ansible.builtin.raw: |
    LOG_FILE="/bigc/log/print_queue_$(hostname)_$(date +%Y%m%d).log"
    # Default monitored print queues - can be overridden via variable
    PRINT_QUEUES="lp0 lp1"
    QUEUES_RESTARTED=0
    DATE_SUFFIX=$(date +%Y%m%d)
    
    if [ -n "$PRINT_QUEUES" ]; then
      echo "Checking individual print queues: $PRINT_QUEUES" >> "$LOG_FILE"
      
      for queue in $PRINT_QUEUES; do
        echo "Checking queue: $queue" >> "$LOG_FILE"
        
        # Check if queue is DOWN
        if lpstat -p"$queue" 2>/dev/null | grep -q DOWN; then
          echo "Found queue $queue was DOWN" >> "$LOG_FILE"
          
          # Create error log for this queue
          ERROR_LOG="/bigc/log/print_queue_error_$(hostname)_${DATE_SUFFIX}.down"
          echo "Found queue $queue was down then" > "$ERROR_LOG"
          lpstat -W -p"$queue" >> "$ERROR_LOG" 2>/dev/null
          echo "" >> "$ERROR_LOG"
          
          # Disable and re-enable the queue
          echo "Restarting queue $queue..." >> "$LOG_FILE"
          if disable "$queue" && enable "$queue"; then
            echo "Successfully restarted queue $queue" >> "$LOG_FILE"
            QUEUES_RESTARTED=$((QUEUES_RESTARTED + 1))
            
            # Wait for queue to come up
            sleep 5
            
            # Complete error log
            echo "" >> "$ERROR_LOG"
            echo "---------------------- By EIS Command Center ----------------------" >> "$ERROR_LOG"
            echo "First action by auto disable and enable on OFI" >> "$ERROR_LOG"
          else
            echo "Failed to restart queue $queue" >> "$LOG_FILE"
          fi
        else
          echo "Queue $queue status is OK" >> "$LOG_FILE"
        fi
      done
      
      # Add post-restart status if any queues were restarted
      if [ "$QUEUES_RESTARTED" -gt 0 ]; then
        echo "" >> "$LOG_FILE"
        echo "=============================== POST AUTO TASKS STATUS ===============================" >> "$LOG_FILE"
        echo "$(date)" >> "$LOG_FILE"
        lpstat -a >> "$LOG_FILE" 2>/dev/null
        echo "" >> "$LOG_FILE"
        echo "Recommended Action: If status: READY/RUNNING, No response action is required." >> "$LOG_FILE"
        echo "Recommended Action: If status: DOWN, Please call to EIS Unix-Linux Admin Team for review" >> "$LOG_FILE"
        echo "" >> "$LOG_FILE"
        echo "---------------------- By EIS Command Center ----------------------" >> "$LOG_FILE"
      fi
    else
      echo "No print queues specified for monitoring" >> "$LOG_FILE"
    fi
    
    echo "QUEUES_RESTARTED=$QUEUES_RESTARTED"
  register: queue_restart
  changed_when: false
  failed_when: false
  tags:
    - print_queue
    - queues

- name: Send email notifications
  ansible.builtin.raw: |
    echo "Email notifications skipped - validation mode"
  when: false
  failed_when: false
  tags:
    - print_queue
    - notification

- name: Display print queue monitoring results
  ansible.builtin.raw: |
    echo "====================================="
    echo "Print queue monitoring completed on $(hostname)"
    echo "Log file: /bigc/log/print_queue_$(hostname)_$(date +%Y%m%d).log"
    echo "====================================="
  tags:
    - print_queue
    - results