---
# Validate GCP Credentials Task

- name: Test GCP credentials and permissions
  google.cloud.gcp_serviceusage_service_info:
    project: "{{ env_config.project_id }}"
  register: gcp_services_info
  
- name: Get GCP project information
  google.cloud.gcp_resourcemanager_project_info:
    project: "{{ env_config.project_id }}"
  register: gcp_project_info

- name: Display GCP credential information
  ansible.builtin.debug:
    msg:
      - "GCP Project ID: {{ gcp_project_info.resources[0].project_id }}"
      - "GCP Project Name: {{ gcp_project_info.resources[0].name }}"
      - "GCP Project Number: {{ gcp_project_info.resources[0].project_number }}"

- name: Test GCP Compute Engine access
  google.cloud.gcp_compute_zone_info:
    project: "{{ env_config.project_id }}"
  register: gcp_zones_test
  failed_when: false

- name: Validate GCP permissions
  ansible.builtin.assert:
    that:
      - gcp_project_info.resources | length > 0
      - gcp_project_info.resources[0].lifecycle_state == "ACTIVE"
      - gcp_zones_test.failed is false
    fail_msg: "GCP credentials are invalid or lack necessary permissions for Compute Engine operations"
    success_msg: "GCP credentials validated successfully"
