---
# Validate Azure Credentials Task

- name: Test Azure credentials and permissions
  azure.azcollection.azure_rm_subscription_info:
  register: azure_subscription_info
  
- name: Display Azure credential information
  ansible.builtin.debug:
    msg:
      - "Azure Subscription ID: {{ azure_subscription_info.subscriptions[0].subscription_id }}"
      - "Azure Tenant ID: {{ azure_subscription_info.subscriptions[0].tenant_id }}"
      - "Azure Subscription Name: {{ azure_subscription_info.subscriptions[0].display_name }}"

- name: Test Azure Resource Group access
  azure.azcollection.azure_rm_resourcegroup_info:
    name: "{{ env_config.resource_group }}"
  register: azure_rg_test
  failed_when: false

- name: Validate Azure permissions
  ansible.builtin.assert:
    that:
      - azure_subscription_info.subscriptions | length > 0
      - azure_subscription_info.subscriptions[0].state == "Enabled"
    fail_msg: "Azure credentials are invalid or subscription is not enabled"
    success_msg: "Azure credentials validated successfully"
