---
# Validate AWS Credentials Task

- name: Test AWS credentials and permissions
  amazon.aws.aws_caller_info:
    region: "{{ env_config.region | default('us-east-1') }}"
  register: aws_caller_info
  
- name: Display AWS credential information
  ansible.builtin.debug:
    msg:
      - "AWS Account ID: {{ aws_caller_info.account }}"
      - "AWS User ARN: {{ aws_caller_info.arn }}"
      - "AWS User ID: {{ aws_caller_info.user_id }}"

- name: Test AWS EC2 access
  amazon.aws.ec2_instance_info:
    region: "{{ env_config.region | default('us-east-1') }}"
  register: ec2_test
  failed_when: false

- name: Validate AWS permissions
  ansible.builtin.assert:
    that:
      - aws_caller_info.account is defined
      - ec2_test.failed is false
    fail_msg: "AWS credentials are invalid or lack necessary permissions for EC2 operations"
    success_msg: "AWS credentials validated successfully"
