# AAP Credential Injection Template
# This template shows the standard AAP credential injection pattern
# to be applied to all AIX-Management playbooks

vars:
  # Playbook identification
  playbook_name: "PLAYBOOK_NAME_HERE"
  playbook_version: "VERSION_HERE"
  
  # AAP Job Information (automatically injected by AAP)
  aap_job_template: "{{ tower_job_template_name | default('N/A') }}"
  aap_job_id: "{{ tower_job_id | default('N/A') }}"
  aap_user: "{{ tower_user_name | default('N/A') }}"
  aap_inventory: "{{ tower_inventory_name | default('N/A') }}"
  
  # Change tracking for AAP
  change_reason: "{{ change_reason | default('AIX system management via AAP') }}"
  change_ticket: "{{ change_ticket | default('') }}"
  
  # Credential status for display
  credential_status: "{{ 'AAP Injected' if ansible_user is defined and ansible_user != '' else 'Manual Configuration' }}"

# Standard pre_tasks section for all playbooks
pre_tasks:
  - name: Display playbook execution information
    ansible.builtin.debug:
      msg: |
        =====================================
        {{ playbook_name }}
        =====================================
        Version: {{ playbook_version }}
        Target Hosts: {{ target_hosts | default(group_names | first | default('aix')) }}
        Batch Size: {{ batch_size | default('1') }}
        
        AAP Integration:
        - Job Template: {{ aap_job_template }}
        - Job ID: {{ aap_job_id }}
        - Executed By: {{ aap_user }}
        - Inventory: {{ aap_inventory }}
        
        Authentication:
        - User: {{ ansible_user | default('Not specified') }}
        - Credential Status: {{ credential_status }}
        
        Change Management:
        - Reason: {{ change_reason }}
        - Ticket: {{ change_ticket | default('Not provided') }}
        
        Execution Details:
        - Start Time: {{ ansible_date_time.iso8601 }}
        - Controller: {{ ansible_control_node | default('Unknown') }}
        =====================================
    tags: always

# Standard post_tasks section for all playbooks  
post_tasks:
  - name: Display playbook completion summary
    ansible.builtin.debug:
      msg: |
        =====================================
        {{ playbook_name }} - COMPLETED
        =====================================
        Execution Summary:
        - Job ID: {{ aap_job_id }}
        - Completed: {{ ansible_date_time.iso8601 }}
        - Status: Success
        - Processed Hosts: {{ ansible_play_hosts | length }}
        
        Change Tracking:
        - Ticket: {{ change_ticket | default('No ticket provided') }}
        - Reason: {{ change_reason }}
        
        Next Steps:
        - Review AAP job logs for detailed results
        - Verify changes on target systems if applicable
        - Update change management system if required
        =====================================
    tags: always
    run_once: true