---
# Main tasks for memory management using direct SSH commands

- name: Ensure log directory exists
  ansible.builtin.raw: |
    [ -d "{{ aix_log_dir }}" ] || mkdir -p "{{ aix_log_dir }}"
    chmod 755 "{{ aix_log_dir }}"
  changed_when: false
  tags:
    - memory
    - setup

- name: Get current paging space usage
  ansible.builtin.raw: |
    # Get paging space usage percentage
    PAGING_USAGE=$(lsps -a 2>/dev/null | tail -1 | awk '{print $5}' | sed 's/%//' || echo "0")
    
    # Get current memory configuration
    MEMORY_INFO=$(prtconf -m 2>/dev/null || echo "Unable to retrieve memory information")
    
    echo "PAGING_USAGE=$PAGING_USAGE"
    echo "MEMORY_INFO_START"
    echo "$MEMORY_INFO"
    echo "MEMORY_INFO_END"
  register: memory_status
  changed_when: false
  tags:
    - memory
    - monitoring

- name: Initialize memory monitoring log
  ansible.builtin.raw: |
    LOG_FILE="/bigc/log/memory_autojob_$(hostname)_$(date +%Y%m%d).log"
    echo "=============================== MEMORY AUTO-SCALING MONITORING ===============================" > "$LOG_FILE"
    echo "Date: $(date)" >> "$LOG_FILE"
    echo "Hostname: $(hostname)" >> "$LOG_FILE"
    echo "Change Ticket: AUTO" >> "$LOG_FILE"
    echo "Change Reason: Automated memory scaling via AAP" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    # Get current paging space usage
    PAGING_VAL=$(lsps -a 2>/dev/null | tail -1 | awk '{print $5}' | sed 's/%//' || echo "0")
    echo "Current paging space usage: $PAGING_VAL%" >> "$LOG_FILE"
    echo "Threshold: 10%" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
  register: memory_log_init
  changed_when: false
  tags:
    - memory
    - logging

- name: Check if memory scaling is needed and execute
  ansible.builtin.raw: |
    LOG_FILE="/bigc/log/memory_autojob_$(hostname)_$(date +%Y%m%d).log"
    MEMORY_THRESHOLD="10"
    HMC_HOST=""
    HMC_USER=""
    HMC_MANAGED_SYSTEM=""
    HMC_PARTITION_NAME=""
    MEMORY_INCREMENT="512"
    HMC_TIMEOUT="30"
    
    # Get current paging space usage
    CURRENT_PAGING=$(lsps -a 2>/dev/null | tail -1 | awk '{print $5}' | sed 's/%//' || echo "0")
    
    echo "Checking if memory scaling is needed..." >> "$LOG_FILE"
    echo "Current Paging Usage: $CURRENT_PAGING%, Threshold: $MEMORY_THRESHOLD%" >> "$LOG_FILE"
    
    if [ "$CURRENT_PAGING" -gt "$MEMORY_THRESHOLD" ] 2>/dev/null; then
      echo "Paging usage $CURRENT_PAGING% exceeds threshold $MEMORY_THRESHOLD% - would initiate memory scaling" >> "$LOG_FILE"
      
      # Get current memory configuration before addition
      echo "Host $(hostname) memory < before add memory >" >> "$LOG_FILE"
      prtconf -m >> "$LOG_FILE" 2>/dev/null || echo "Unable to retrieve memory information" >> "$LOG_FILE"
      echo "Would auto increase memory $MEMORY_INCREMENT MB to $(hostname)" >> "$LOG_FILE"
      echo "" >> "$LOG_FILE"
      
      # Simulate memory scaling for validation
      echo "[SIMULATION] Would execute HMC command for memory scaling" >> "$LOG_FILE"
      echo "[SIMULATION] HMC configuration not available in validation mode" >> "$LOG_FILE"
      echo "" >> "$LOG_FILE"
      echo "Recommended Action: This is a validation run - no actual scaling performed" >> "$LOG_FILE"
      echo "" >> "$LOG_FILE"
      echo "---------------------- By EIS Command Center ----------------------" >> "$LOG_FILE"
      
      echo "MEMORY_SCALED=NO"
    else
      echo "Paging usage $CURRENT_PAGING% within threshold $MEMORY_THRESHOLD% - no scaling needed" >> "$LOG_FILE"
      echo "MEMORY_SCALED=NO"
    fi
  register: memory_scaling
  changed_when: false
  failed_when: false
  tags:
    - memory
    - scaling

- name: Send email notification if memory was scaled
  ansible.builtin.raw: |
    LOG_FILE="/bigc/log/memory_autojob_$(hostname)_$(date +%Y%m%d).log"
    echo "Email notification skipped - validation mode" >> "$LOG_FILE"
  when: false
  failed_when: false
  tags:
    - memory
    - notification

- name: Display memory monitoring results
  ansible.builtin.raw: |
    echo "====================================="
    echo "Memory monitoring completed on $(hostname)"
    PAGING=$(lsps -a 2>/dev/null | tail -1 | awk '{print $5}' | sed 's/%//' || echo "0")
    echo "Current Paging Usage: $PAGING%"
    echo "Threshold: 10%"
    echo "Log file: /bigc/log/memory_autojob_$(hostname)_$(date +%Y%m%d).log"
    echo "====================================="
  tags:
    - memory
    - results