# Example: Prefilled Survey Variables for Reuse
#
# Copy this file and fill in your values. Then, reference it in your playbook using `vars_files`.
#
# Example usage in a playbook:
#   vars_files:
#     - ../prefilled-survey-vars.yml

cloud_provider: aws
region: us-east-1
resource_group: my-resource-group
gcp_project: my-gcp-project
server_name: my-server
image_id: ami-12345678
instance_type: t2.micro
admin_username: ec2-user
image_offer: UbuntuServer
image_publisher: Canonical
image_sku: 18.04-LTS
image_version: latest
pvc_name: my-volume
size: 10Gi
storage_class: standard
access_modes: ReadWriteOnce
namespace: default
security_group_name: my-sg
security_rules: []
unused_resource_output_file: unused_resources.json
cloud_auth_file: cloud_auth.yml
vault_password_file: vault_pass.txt
aws_access_key: YOUR_AWS_ACCESS_KEY
aws_secret_key: YOUR_AWS_SECRET_KEY
aws_session_token: ''
azure_client_id: YOUR_AZURE_CLIENT_ID
azure_secret: YOUR_AZURE_SECRET
azure_tenant: YOUR_AZURE_TENANT_ID
azure_subscription_id: YOUR_AZURE_SUBSCRIPTION_ID
gcp_service_account_json: |
  {
    "type": "service_account",
    "project_id": "my-gcp-project",
    ...
  }
