---
# tasks file for cloud_query_unused
- name: Set cloud provider fact
  set_fact:
    selected_cloud: "{{ cloud_provider | lower }}"

- name: Set date thresholds
  set_fact:
    threshold_30: "{{ (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')).replace(hour=0, minute=0, second=0, microsecond=0) - 30 * 24 * 60 * 60 }}"
    threshold_60: "{{ (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')).replace(hour=0, minute=0, second=0, microsecond=0) - 60 * 24 * 60 * 60 }}"
    threshold_90: "{{ (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')).replace(hour=0, minute=0, second=0, microsecond=0) - 90 * 24 * 60 * 60 }}"

- name: Query unused AWS resources (stopped EC2 instances)
  when: selected_cloud == 'aws'
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      instance-state-name: ["stopped"]
  register: aws_unused_result

- name: Filter AWS EC2 by last used time
  when: selected_cloud == 'aws'
  set_fact:
    aws_unused_by_age:
      over_30_days: "{{ aws_unused_result.instances | selectattr('launch_time', 'defined') | selectattr('launch_time', 'lt', threshold_30) | list }}"
      over_60_days: "{{ aws_unused_result.instances | selectattr('launch_time', 'defined') | selectattr('launch_time', 'lt', threshold_60) | list }}"
      over_90_days: "{{ aws_unused_result.instances | selectattr('launch_time', 'defined') | selectattr('launch_time', 'lt', threshold_90) | list }}"

- name: Query unused Azure resources (deallocated VMs)
  when: selected_cloud == 'azure'
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{ resource_group }}"
  register: azure_vm_info

- name: Filter deallocated Azure VMs
  when: selected_cloud == 'azure'
  set_fact:
    azure_unused_result: "{{ azure_vm_info.virtual_machines | selectattr('power_state', 'equalto', 'deallocated') | list }}"

- name: Filter Azure VMs by last used time
  when: selected_cloud == 'azure'
  set_fact:
    azure_unused_by_age:
      over_30_days: "{{ azure_unused_result | selectattr('time_created', 'defined') | selectattr('time_created', 'lt', threshold_30) | list }}"
      over_60_days: "{{ azure_unused_result | selectattr('time_created', 'defined') | selectattr('time_created', 'lt', threshold_60) | list }}"
      over_90_days: "{{ azure_unused_result | selectattr('time_created', 'defined') | selectattr('time_created', 'lt', threshold_90) | list }}"

- name: Query unused GCP resources (TERMINATED instances)
  when: selected_cloud == 'gcp'
  google.cloud.gcp_compute_instance_info:
    project: "{{ gcp_project }}"
    zone: "{{ region }}"
  register: gcp_vm_info

- name: Filter terminated GCP instances
  when: selected_cloud == 'gcp'
  set_fact:
    gcp_unused_result: "{{ gcp_vm_info.resources | selectattr('status', 'equalto', 'TERMINATED') | list }}"

- name: Filter GCP instances by last used time
  when: selected_cloud == 'gcp'
  set_fact:
    gcp_unused_by_age:
      over_30_days: "{{ gcp_unused_result | selectattr('creationTimestamp', 'defined') | selectattr('creationTimestamp', 'lt', threshold_30) | list }}"
      over_60_days: "{{ gcp_unused_result | selectattr('creationTimestamp', 'defined') | selectattr('creationTimestamp', 'lt', threshold_60) | list }}"
      over_90_days: "{{ gcp_unused_result | selectattr('creationTimestamp', 'defined') | selectattr('creationTimestamp', 'lt', threshold_90) | list }}"

- name: Display unused resources by age
  debug:
    msg: |
      {% if selected_cloud == 'aws' %}
        AWS EC2 Instances unused over 30 days: {{ aws_unused_by_age.over_30_days }}
        AWS EC2 Instances unused over 60 days: {{ aws_unused_by_age.over_60_days }}
        AWS EC2 Instances unused over 90 days: {{ aws_unused_by_age.over_90_days }}
      {% elif selected_cloud == 'azure' %}
        Azure VMs unused over 30 days: {{ azure_unused_by_age.over_30_days }}
        Azure VMs unused over 60 days: {{ azure_unused_by_age.over_60_days }}
        Azure VMs unused over 90 days: {{ azure_unused_by_age.over_90_days }}
      {% elif selected_cloud == 'gcp' %}
        GCP Instances unused over 30 days: {{ gcp_unused_by_age.over_30_days }}
        GCP Instances unused over 60 days: {{ gcp_unused_by_age.over_60_days }}
        GCP Instances unused over 90 days: {{ gcp_unused_by_age.over_90_days }}
      {% else %}
        No valid cloud provider selected.
      {% endif %}

- name: Send unused resources by age report via email
  community.general.mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port | default(587) }}"
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    to: "{{ report_email_to }}"
    from: "{{ report_email_from }}"
    subject: "Cloud Unused Resource Report"
    subtype: html
    body: |
      <h2>Cloud Unused Resource Report</h2>
      <pre>
      {% if selected_cloud == 'aws' %}
        AWS EC2 Instances unused over 30 days: {{ aws_unused_by_age.over_30_days | to_nice_json }}
        AWS EC2 Instances unused over 60 days: {{ aws_unused_by_age.over_60_days | to_nice_json }}
        AWS EC2 Instances unused over 90 days: {{ aws_unused_by_age.over_90_days | to_nice_json }}
      {% elif selected_cloud == 'azure' %}
        Azure VMs unused over 30 days: {{ azure_unused_by_age.over_30_days | to_nice_json }}
        Azure VMs unused over 60 days: {{ azure_unused_by_age.over_60_days | to_nice_json }}
        Azure VMs unused over 90 days: {{ azure_unused_by_age.over_90_days | to_nice_json }}
      {% elif selected_cloud == 'gcp' %}
        GCP Instances unused over 30 days: {{ gcp_unused_by_age.over_30_days | to_nice_json }}
        GCP Instances unused over 60 days: {{ gcp_unused_by_age.over_60_days | to_nice_json }}
        GCP Instances unused over 90 days: {{ gcp_unused_by_age.over_90_days | to_nice_json }}
      {% else %}
        No valid cloud provider selected.
      {% endif %}
      </pre>
  delegate_to: localhost
  when: report_email_to is defined and report_email_from is defined and smtp_host is defined
