---
# AIX Memory Management Playbook
# Monitors paging space usage and automatically adds memory via HMC when thresholds are exceeded
# Compatible with AAP 2.5 and includes credential injection

- name: AIX Memory Management and Auto-scaling
  hosts: "{{ target_hosts | default('aix') }}"
  gather_facts: true
  become: true
  
  vars:
    # Playbook identification for AAP
    playbook_name: "AIX Memory Management"
    playbook_version: "2.0"
    
    # AAP Job Information (automatically injected by AAP)
    aap_job_template: "{{ tower_job_template_name | default('N/A') }}"
    aap_job_id: "{{ tower_job_id | default('N/A') }}"
    aap_user: "{{ tower_user_name | default('N/A') }}"
    aap_inventory: "{{ tower_inventory_name | default('N/A') }}"
    
    # Change tracking for AAP
    change_reason: "{{ change_reason | default('Automated memory monitoring and scaling') }}"
    change_ticket: "{{ change_ticket | default('') }}"
    
    # Credential status for display
    credential_status: "{{ 'AAP Injected' if ansible_user is defined and ansible_user != '' else 'Manual Configuration' }}"
    
    # Override thresholds if provided via survey
    memory_threshold_override: "{{ memory_threshold | default(omit) }}"
    memory_increment_override: "{{ memory_increment | default(omit) }}"
    
  pre_tasks:
    - name: Display playbook information
      ansible.builtin.debug:
        msg: |
          =====================================
          AIX Memory Management Playbook
          =====================================
          Version: {{ playbook_version }}
          Target Hosts: {{ target_hosts | default('aix') }}
          AAP Job Template: {{ aap_job_template }}
          AAP Job ID: {{ aap_job_id }}
          AAP User: {{ aap_user }}
          Change Reason: {{ change_reason }}
          Change Ticket: {{ change_ticket }}
          HMC Host: {{ hmc_host }}
          =====================================
      tags: always
    
    - name: Validate target hosts
      ansible.builtin.fail:
        msg: "No valid AIX hosts found in inventory"
      when: ansible_system is not defined or ansible_system != "AIX"
      tags: always
    
    - name: Set memory threshold if provided
      ansible.builtin.set_fact:
        memory_threshold: "{{ memory_threshold_override }}"
      when: memory_threshold_override is defined
      tags: always
    
    - name: Set memory increment if provided
      ansible.builtin.set_fact:
        memory_increment_mb: "{{ memory_increment_override }}"
      when: memory_increment_override is defined
      tags: always
    
    - name: Validate HMC connectivity
      ansible.builtin.wait_for:
        host: "{{ hmc_host }}"
        port: 22
        timeout: 10
      delegate_to: localhost
      when: memory_auto_scaling_enabled | bool
      tags: always

  roles:
    - role: memory_management
      tags:
        - memory
        - monitoring
        - auto_scaling
        - hmc
        - paging
  
  post_tasks:
    - name: Generate summary report
      ansible.builtin.debug:
        msg: |
          =====================================
          Memory Management Summary
          =====================================
          Host: {{ ansible_hostname }}
          Execution Time: {{ ansible_date_time.iso8601 }}
          Paging Threshold: {{ memory_threshold }}%
          Memory Increment: {{ memory_increment_mb }}MB
          Auto-scaling Enabled: {{ memory_auto_scaling_enabled }}
          HMC Integration: {{ hmc_host }}
          Status: Completed successfully
          =====================================
      tags: always