---
# AIX Complete Monitoring Playbook
# Comprehensive monitoring and management of all AIX system components
# Compatible with AAP 2.5 and includes credential injection

- name: AIX Complete System Monitoring and Management
  hosts: "{{ target_hosts | default('aix') }}"
  gather_facts: false
  become: true
  serial: "{{ batch_size | default(1) }}"
  
  vars:
    # Playbook identification for AAP
    playbook_name: "AIX Complete Monitoring"
    playbook_version: "2.0"
    
    # AAP Job Information (automatically injected by AAP)
    aap_job_template: "{{ tower_job_template_name | default('N/A') }}"
    aap_job_id: "{{ tower_job_id | default('N/A') }}"
    aap_user: "{{ tower_user_name | default('N/A') }}"
    aap_inventory: "{{ tower_inventory_name | default('N/A') }}"
    
    # Change tracking for AAP (avoid recursive definition)
    complete_change_reason: "{{ change_reason | default('Comprehensive AIX system monitoring and management') }}"
    complete_change_ticket: "{{ change_ticket | default('') }}"
    
    # Credential status for display
    credential_status: "{{ 'AAP Injected' if ansible_user is defined and ansible_user != '' else 'Manual Configuration' }}"
    
    # Service selection (can be overridden via survey)
    enable_filesystem_monitoring: "{{ filesystem_monitoring | default(true) }}"
    enable_cpu_monitoring: "{{ cpu_monitoring | default(true) }}"
    enable_memory_monitoring: "{{ memory_monitoring | default(true) }}"
    enable_print_queue_monitoring: "{{ print_queue_monitoring | default(true) }}"
    enable_service_monitoring: "{{ service_monitoring | default(true) }}"
    
  pre_tasks:
    - name: Gather minimal system facts
      ansible.builtin.raw: |
        echo "HOSTNAME=$(hostname)"
        echo "OS=$(uname -s)"
        echo "DATE=$(date)"
      register: system_info
      changed_when: false
      tags: always
    
    - name: Display playbook execution information
      ansible.builtin.debug:
        msg: |
          =====================================
          {{ playbook_name }}
          =====================================
          Version: {{ playbook_version }}
          Target Hosts: {{ target_hosts | default(group_names | first | default('aix')) }}
          Batch Size: {{ batch_size | default('1') }}
          
          AAP Integration:
          - Job Template: {{ aap_job_template }}
          - Job ID: {{ aap_job_id }}
          - Executed By: {{ aap_user }}
          - Inventory: {{ aap_inventory }}
          
          Authentication:
          - User: {{ ansible_user | default('Not specified') }}
          - Credential Status: {{ credential_status }}
          
          Change Management:
          - Reason: {{ complete_change_reason }}
          - Ticket: {{ complete_change_ticket | default('Not provided') }}
          
          Service Configuration:
          - Filesystem: {{ enable_filesystem_monitoring }}
          - CPU: {{ enable_cpu_monitoring }}
          - Memory: {{ enable_memory_monitoring }}
          - Print Queue: {{ enable_print_queue_monitoring }}
          - Service Monitoring: {{ enable_service_monitoring }}
          
          Execution Details:
          - Start Time: {{ system_info.stdout_lines | select('match', '^DATE=') | first | regex_replace('DATE=', '') | default('N/A') }}
          - Controller: {{ ansible_control_node | default('Unknown') }}
          =====================================
      tags: always
    
    - name: Validate target hosts
      ansible.builtin.fail:
        msg: "No valid AIX hosts found in inventory"
      when: "'OS=AIX' not in system_info.stdout"
      tags: always
    
    - name: Record monitoring start time
      ansible.builtin.raw: |
        echo "MONITORING_START_TIME=$(date +%Y-%m-%dT%H:%M:%SZ)"
      register: start_time_info
      changed_when: false
      tags: always

  tasks:
    - name: Execute Filesystem Management
      include_role:
        name: filesystem_management
      when: enable_filesystem_monitoring | bool
      tags:
        - filesystem
        - monitoring
    
    - name: Execute CPU Management
      include_role:
        name: cpu_management
      when: enable_cpu_monitoring | bool
      tags:
        - cpu
        - monitoring
        - hmc
    
    - name: Execute Memory Management
      include_role:
        name: memory_management
      when: enable_memory_monitoring | bool
      tags:
        - memory
        - monitoring
        - hmc
    
    - name: Execute Print Queue Management
      include_role:
        name: print_queue_management
      when: enable_print_queue_monitoring | bool
      tags:
        - print_queue
        - monitoring
    
    - name: Execute Service Monitoring
      include_role:
        name: service_monitoring
      when: enable_service_monitoring | bool
      tags:
        - service_monitoring
        - zabbix
  
  post_tasks:
    - name: Get current time for duration calculation
      ansible.builtin.raw: |
        echo "EXECUTION_END_TIME=$(date +%Y-%m-%dT%H:%M:%SZ)"
      register: end_time_info
      changed_when: false
      tags: always
    
    - name: Generate comprehensive summary report
      ansible.builtin.debug:
        msg: |
          =====================================
          Complete Monitoring Summary Report
          =====================================
          Host: {{ system_info.stdout_lines | select('match', '^HOSTNAME=') | first | regex_replace('HOSTNAME=', '') | default('unknown') }}
          Start Time: {{ start_time_info.stdout_lines | select('match', '^MONITORING_START_TIME=') | first | regex_replace('MONITORING_START_TIME=', '') | default('N/A') }}
          End Time: {{ end_time_info.stdout_lines | select('match', '^EXECUTION_END_TIME=') | first | regex_replace('EXECUTION_END_TIME=', '') | default('N/A') }}
          Duration: Completed successfully
          
          Service Status:
          - Filesystem Monitoring: {{ 'EXECUTED' if enable_filesystem_monitoring else 'SKIPPED' }}
          - CPU Monitoring: {{ 'EXECUTED' if enable_cpu_monitoring else 'SKIPPED' }}
          - Memory Monitoring: {{ 'EXECUTED' if enable_memory_monitoring else 'SKIPPED' }}
          - Print Queue Monitoring: {{ 'EXECUTED' if enable_print_queue_monitoring else 'SKIPPED' }}
          - Service Monitoring: {{ 'EXECUTED' if enable_service_monitoring else 'SKIPPED' }}
          
          Overall Status: COMPLETED SUCCESSFULLY
          =====================================
      tags: always
    
    - name: Send completion notification
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_pass }}"
        to: "{{ alert_emails }}"
        subject: "EIS Command Center: AIX Complete Monitoring completed on {{ ansible_hostname }}"
        body: |
          AIX Complete System Monitoring has been completed successfully.
          
          Host: {{ system_info.stdout_lines | select('match', '^HOSTNAME=') | first | regex_replace('HOSTNAME=', '') | default('unknown') }}
          Execution Time: {{ end_time_info.stdout_lines | select('match', '^EXECUTION_END_TIME=') | first | regex_replace('EXECUTION_END_TIME=', '') | default('N/A') }}
          Duration: Completed successfully
          AAP Job ID: {{ aap_job_id }}
          
          All enabled monitoring services have been executed.
      when: 
        - alert_emails is defined
        - send_completion_email | default(false) | bool
      tags: always

  post_tasks:
    - name: Display playbook completion summary
      ansible.builtin.debug:
        msg: |
          =====================================
          {{ playbook_name }} - COMPLETED
          =====================================
          Execution Summary:
          - Job ID: {{ aap_job_id }}
          - Completed: {{ end_time_info.stdout_lines | select('match', '^EXECUTION_END_TIME=') | first | regex_replace('EXECUTION_END_TIME=', '') | default('N/A') }}
          - Status: Success
          - Processed Hosts: 1
          
          Service Execution Status:
          - Filesystem Monitoring: {{ 'EXECUTED' if enable_filesystem_monitoring else 'SKIPPED' }}
          - CPU Monitoring: {{ 'EXECUTED' if enable_cpu_monitoring else 'SKIPPED' }}
          - Memory Monitoring: {{ 'EXECUTED' if enable_memory_monitoring else 'SKIPPED' }}
          - Print Queue Monitoring: {{ 'EXECUTED' if enable_print_queue_monitoring else 'SKIPPED' }}
          - Service Monitoring: {{ 'EXECUTED' if enable_service_monitoring else 'SKIPPED' }}
          
          Change Tracking:
          - Ticket: {{ change_ticket | default('No ticket provided') }}
          - Reason: {{ complete_change_reason }}
          
          Next Steps:
          - Review AAP job logs for detailed results
          - Verify monitoring configurations on target systems
          - Update change management system if required
          =====================================
      tags: always
      run_once: true