---
# AIX Print Queue Management Playbook
# Monitors print queues and spooler services with automatic restart capabilities
# Compatible with AAP 2.5 and includes credential injection

- name: AIX Print Queue and Spooler Management
  hosts: "{{ target_hosts | default('aix') }}"
  gather_facts: false
  become: true
  
  vars:
    # Playbook identification for AAP
    playbook_name: "AIX Print Queue Management"
    playbook_version: "2.0"
    
    # AAP Job Information (automatically injected by AAP)
    aap_job_template: "{{ tower_job_template_name | default('N/A') }}"
    aap_job_id: "{{ tower_job_id | default('N/A') }}"
    aap_user: "{{ tower_user_name | default('N/A') }}"
    aap_inventory: "{{ tower_inventory_name | default('N/A') }}"
    
    # Change tracking for AAP (avoid recursive definition)
    pq_change_reason: "{{ change_reason | default('Automated print queue monitoring and restart') }}"
    pq_change_ticket: "{{ change_ticket | default('') }}"
    
    # Credential status for display
    credential_status: "{{ 'AAP Injected' if ansible_user is defined and ansible_user != '' else 'Manual Configuration' }}"
    
    # Override queues if provided via survey
    print_queues_override: "{{ print_queues | default([]) }}"
    
  pre_tasks:
    - name: Gather minimal system facts
      ansible.builtin.raw: |
        echo "HOSTNAME=$(hostname)"
        echo "OS=$(uname -s)"
      register: system_info
      changed_when: false
      tags: always
    
    - name: Display playbook information
      ansible.builtin.debug:
        msg: |
          =====================================
          AIX Print Queue Management Playbook
          =====================================
          Version: {{ playbook_version }}
          Target Hosts: {{ target_hosts | default('aix') }}
          AAP Job Template: {{ aap_job_template }}
          AAP Job ID: {{ aap_job_id }}
          AAP User: {{ aap_user }}
          Change Reason: {{ pq_change_reason }}
          Change Ticket: {{ pq_change_ticket }}
          =====================================
      tags: always
    
    - name: Validate target hosts
      ansible.builtin.fail:
        msg: "No valid AIX hosts found in inventory"
      when: "'OS=AIX' not in system_info.stdout"
      tags: always
    
    - name: Set print queues if provided
      ansible.builtin.set_fact:
        print_queues_to_monitor: "{{ print_queues_override }}"
      when: 
        - print_queues_override is defined
        - print_queues_override | length > 0
      tags: always

  roles:
    - role: print_queue_management
      tags:
        - print_queue
        - spooler
        - monitoring
        - restart
  
  post_tasks:
    - name: Generate summary report
      ansible.builtin.debug:
        msg: |
          =====================================
          Print Queue Management Summary
          =====================================
          Host: {{ system_info.stdout_lines | select('match', '^HOSTNAME=') | first | regex_replace('HOSTNAME=', '') | default('unknown') }}
          Execution Time: {{ ansible_date_time.iso8601 if ansible_date_time is defined else 'N/A' }}
          Monitored Queues: {{ print_queues_to_monitor | default(['default']) | join(', ') }}
          Spooler Monitoring: {{ spooler_monitoring_enabled | default(true) }}
          Auto-restart Enabled: {{ auto_restart_enabled | default(true) }}
          Status: Completed successfully
          =====================================
      tags: always