---
# AIX Connectivity Test Playbook - Enhanced with AIX Modules
# Uses IBM Power AIX collection modules where appropriate
# Falls back to generic modules for basic connectivity

- name: AIX Enhanced Connectivity Test
  hosts: "{{ target_hosts | default('aix') }}"
  gather_facts: false
  serial: "{{ batch_size | default(5) }}"
  
  vars:
    # Playbook identification
    playbook_name: "AIX Enhanced Connectivity Test"
    playbook_version: "2.0"
    
    # Test configuration
    test_user: "{{ ansible_user | default('root') }}"
    connection_timeout: "{{ timeout | default(30) }}"
    
    # AAP Job Information (automatically injected by AAP)
    aap_job_template: "{{ tower_job_template_name | default('N/A') }}"
    aap_job_id: "{{ tower_job_id | default('N/A') }}"
    aap_user: "{{ tower_user_name | default('N/A') }}"
    
  tasks:
    - name: Display test information
      ansible.builtin.debug:
        msg: |
          =====================================
          AIX Enhanced Connectivity Test
          =====================================
          Version: {{ playbook_version }}
          Target Host: {{ inventory_hostname }}
          Test User: {{ test_user }}
          Connection Timeout: {{ connection_timeout }}s
          AAP Job Template: {{ aap_job_template }}
          AAP Job ID: {{ aap_job_id }}
          AAP User: {{ aap_user }}
          Credential Status: {{ 'Injected' if ansible_user is defined and ansible_user != '' else 'Manual' }}
          =====================================
      delegate_to: localhost
      run_once: false

    - name: Test 1 - Basic ping connectivity
      ansible.builtin.ping:
      register: ping_result
      failed_when: false
      tags: basic

    - name: Display ping result
      ansible.builtin.debug:
        msg: "✅ Ping test: {{ 'PASSED' if ping_result is succeeded else 'FAILED' }}"
      tags: basic

    - name: Test 2 - Gather basic system facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "min"
          - "system"
          - "network"
      register: facts_result
      failed_when: false
      tags: facts

    - name: Display system information
      ansible.builtin.debug:
        msg: |
          System Information:
          - Hostname: {{ ansible_hostname | default('Unknown') }}
          - OS: {{ ansible_system | default('Unknown') }}
          - Architecture: {{ ansible_architecture | default('Unknown') }}
          - Kernel: {{ ansible_kernel | default('Unknown') }}
          - IP Address: {{ ansible_default_ipv4.address | default('Unknown') }}
      when: facts_result is succeeded
      tags: facts

    - name: Test 3 - Get AIX system configuration using raw commands
      ansible.builtin.raw: |
        echo "KERNEL_BITMODE=$(getconf KERNEL_BITMODE 2>/dev/null || echo 'Unknown')"
        echo "HARDWARE_BITMODE=$(getconf HARDWARE_BITMODE 2>/dev/null || echo 'Unknown')"
        echo "REAL_MEMORY_KB=$(getconf _SC_AIX_REALMEM 2>/dev/null || echo 'Unknown')"
        echo "ONLINE_CPUS=$(getconf _SC_NPROCESSORS_ONLN 2>/dev/null || echo 'Unknown')"
      register: aix_config
      failed_when: false
      changed_when: false
      tags: aix

    - name: Display AIX configuration
      ansible.builtin.debug:
        msg: |
          ✅ AIX System Configuration:
          {{ aix_config.stdout | default('Unable to retrieve system configuration') }}
      when: aix_config is succeeded
      tags: aix

    - name: Test 4 - Get LPAR information using raw commands
      ansible.builtin.raw: |
        echo "LPAR Information:"
        lparstat -i 2>/dev/null | head -10 || echo "Unable to retrieve LPAR information"
      register: lpar_info
      failed_when: false
      changed_when: false
      tags: lpar

    - name: Display LPAR information
      ansible.builtin.debug:
        msg: |
          ✅ LPAR Information:
          {{ lpar_info.stdout | default('Unable to retrieve LPAR information') }}
      when: lpar_info is succeeded
      tags: lpar

    - name: Test 5 - Check filesystem information using raw commands
      ansible.builtin.raw: |
        echo "Filesystem Information:"
        df -h / 2>/dev/null || echo "Unable to retrieve filesystem information"
        echo ""
        echo "Mount Information:"
        mount | grep "^/dev" | head -5 2>/dev/null || echo "Unable to retrieve mount information"
      register: filesystem_info
      failed_when: false
      changed_when: false
      tags: filesystem

    - name: Display filesystem usage
      ansible.builtin.debug:
        msg: |
          ✅ Filesystem Status:
          {{ filesystem_info.stdout | default('Unable to determine filesystem usage') }}
      when: filesystem_info is succeeded
      tags: filesystem

    - name: Test 6 - Get LVM information using raw commands
      ansible.builtin.raw: |
        echo "LVM Information:"
        echo "Volume Groups:"
        lsvg 2>/dev/null || echo "Unable to retrieve volume group information"
        echo ""
        echo "Physical Volumes:"
        lspv 2>/dev/null || echo "Unable to retrieve physical volume information"
      register: lvm_info
      failed_when: false
      changed_when: false
      tags: lvm

    - name: Display LVM information
      ansible.builtin.debug:
        msg: |
          ✅ LVM Information:
          {{ lvm_info.stdout | default('Unable to retrieve LVM information') }}
      when: lvm_info is succeeded
      tags: lvm

    - name: Test 7 - Check for recent system errors using raw commands
      ansible.builtin.raw: |
        echo "Recent System Errors (last 10):"
        errpt | head -10 2>/dev/null || echo "Unable to retrieve error report or no errpt command available"
      register: error_report
      failed_when: false
      changed_when: false
      tags: errors

    - name: Display recent errors
      ansible.builtin.debug:
        msg: |
          ✅ Recent System Errors:
          {{ error_report.stdout | default('Unable to determine') }}
      when: error_report is defined
      tags: errors

    - name: Test 8 - Check SSH user privileges
      ansible.builtin.command: whoami
      register: current_user
      failed_when: false
      changed_when: false
      tags: auth

    - name: Display current user
      ansible.builtin.debug:
        msg: "✅ Connected as user: {{ current_user.stdout | default('Unknown') }}"
      when: current_user is succeeded and current_user.stdout is defined
      tags: auth

    - name: Test 9 - Check sudo access (if not root)
      ansible.builtin.command: sudo -n whoami
      register: sudo_test
      failed_when: false
      changed_when: false
      when: current_user is succeeded and current_user.stdout is defined and current_user.stdout != "root"
      tags: auth

    - name: Display sudo status
      ansible.builtin.debug:
        msg: "✅ Sudo access: {{ 'Available' if sudo_test is succeeded else 'Not available or requires password' }}"
      when: current_user is succeeded and current_user.stdout is defined and current_user.stdout != "root" and sudo_test is defined
      tags: auth

    - name: Test 10 - Get software information using raw commands
      ansible.builtin.raw: |
        echo "Installed Software Information:"
        echo "AIX Version:"
        oslevel -r 2>/dev/null || echo "Unable to determine AIX version"
        echo ""
        echo "Key Software Packages:"
        lslpp -L | grep -E "bos.rte|openssh|sudo" 2>/dev/null | head -5 || echo "Unable to retrieve package information"
      register: software_info
      failed_when: false
      changed_when: false
      tags: software

    - name: Display key software packages
      ansible.builtin.debug:
        msg: |
          ✅ Software Information:
          {{ software_info.stdout | default('Unable to retrieve software information') }}
      when: software_info is succeeded
      tags: software

    - name: Final connectivity summary
      ansible.builtin.debug:
        msg: |
          =====================================
          Enhanced Connectivity Test Summary for {{ inventory_hostname }}
          =====================================
          Basic Tests:
          Ping Test: {{ '✅ PASSED' if ping_result is succeeded else '❌ FAILED' }}
          Facts Gathering: {{ '✅ PASSED' if facts_result is succeeded else '❌ FAILED' }}
          User Authentication: {{ '✅ PASSED' if current_user is succeeded else '❌ FAILED' }}
          
          AIX-Specific Tests (Raw Commands):
          System Configuration: {{ '✅ PASSED' if aix_config is succeeded else '❌ FAILED' }}
          LPAR Information: {{ '✅ PASSED' if lpar_info is succeeded else '❌ FAILED' }}
          Filesystem Check: {{ '✅ PASSED' if filesystem_info is succeeded else '❌ FAILED' }}
          LVM Information: {{ '✅ PASSED' if lvm_info is succeeded else '❌ FAILED' }}
          Error Report Check: {{ '✅ PASSED' if error_report is defined else '❌ FAILED' }}
          Software Information: {{ '✅ PASSED' if software_info is succeeded else '❌ FAILED' }}
          
          Overall Status: {{ 'CONNECTIVITY AND AIX COMMANDS VERIFIED' if (ping_result is succeeded and facts_result is succeeded and current_user is succeeded and aix_config is succeeded) else 'ISSUES DETECTED - CHECK INDIVIDUAL TESTS' }}
          =====================================
      tags: always