---
# AIX Service Monitoring Playbook
# Monitors services like Zabbix agent and provides automatic restart capabilities
# Compatible with AAP 2.5 and includes credential injection

- name: AIX Service Monitoring and Management
  hosts: "{{ target_hosts | default('aix') }}"
  gather_facts: false
  become: true
  
  vars:
    # Playbook identification for AAP
    playbook_name: "AIX Service Monitoring"
    playbook_version: "2.0"
    
    # AAP Job Information (automatically injected by AAP)
    aap_job_template: "{{ tower_job_template_name | default('N/A') }}"
    aap_job_id: "{{ tower_job_id | default('N/A') }}"
    aap_user: "{{ tower_user_name | default('N/A') }}"
    aap_inventory: "{{ tower_inventory_name | default('N/A') }}"
    
    # Change tracking for AAP (avoid recursive definition)
    svc_change_reason: "{{ change_reason | default('Automated service monitoring and restart') }}"
    svc_change_ticket: "{{ change_ticket | default('') }}"
    
    # Credential status for display
    credential_status: "{{ 'AAP Injected' if ansible_user is defined and ansible_user != '' else 'Manual Configuration' }}"
    
    # Override services if provided via survey
    monitored_services_override: "{{ monitored_services | default(['zabbix_agentd']) }}"
    
  pre_tasks:
    - name: Gather minimal system facts
      ansible.builtin.raw: |
        echo "HOSTNAME=$(hostname)"
        echo "OS=$(uname -s)"
      register: system_info
      changed_when: false
      tags: always
    
    - name: Display playbook information
      ansible.builtin.debug:
        msg: |
          =====================================
          AIX Service Monitoring Playbook
          =====================================
          Version: {{ playbook_version }}
          Target Hosts: {{ target_hosts | default('aix') }}
          AAP Job Template: {{ aap_job_template }}
          AAP Job ID: {{ aap_job_id }}
          AAP User: {{ aap_user }}
          Change Reason: {{ svc_change_reason }}
          Change Ticket: {{ svc_change_ticket }}
          =====================================
      tags: always
    
    - name: Validate target hosts
      ansible.builtin.fail:
        msg: "No valid AIX hosts found in inventory"
      when: "'OS=AIX' not in system_info.stdout"
      tags: always

  roles:
    - role: service_monitoring
      tags:
        - service_monitoring
        - zabbix
        - monitoring
        - restart
  
  post_tasks:
    - name: Generate summary report
      ansible.builtin.debug:
        msg: |
          =====================================
          Service Monitoring Summary
          =====================================
          Host: {{ system_info.stdout_lines | select('match', '^HOSTNAME=') | first | regex_replace('HOSTNAME=', '') | default('unknown') }}
          Execution Time: {{ ansible_date_time.iso8601 if ansible_date_time is defined else 'N/A' }}
          Service Monitoring: {{ service_monitoring_enabled | default(true) }}
          Auto-restart Enabled: {{ auto_restart_enabled | default(true) }}
          Monitored Services: {{ monitored_services_override | default(['zabbix_agentd']) | join(', ') }}
          Status: Completed successfully
          =====================================
      tags: always