---
# AIX Memory Management Playbook
# Monitors paging space usage and automatically adds memory via HMC when thresholds are exceeded
# Compatible with AAP 2.5 and includes credential injection

- name: AIX Memory Management and Auto-scaling
  hosts: "{{ target_hosts | default('aix') }}"
  gather_facts: false
  become: true
  
  vars:
    # Playbook identification for AAP
    playbook_name: "AIX Memory Management"
    playbook_version: "2.0"
    
    # AAP Job Information (automatically injected by AAP)
    aap_job_template: "{{ tower_job_template_name | default('N/A') }}"
    aap_job_id: "{{ tower_job_id | default('N/A') }}"
    aap_user: "{{ tower_user_name | default('N/A') }}"
    aap_inventory: "{{ tower_inventory_name | default('N/A') }}"
    
    # Change tracking for AAP (avoid recursive definition)
    memory_change_reason: "{{ change_reason | default('Automated memory monitoring and scaling') }}"
    memory_change_ticket: "{{ change_ticket | default('') }}"
    
    # Override thresholds if provided via survey
    memory_threshold_override: "{{ memory_threshold | default(10) }}"
    memory_increment_override: "{{ memory_increment | default(512) }}"
    
  pre_tasks:
    - name: Gather minimal system facts
      ansible.builtin.raw: |
        echo "HOSTNAME=$(hostname)"
        echo "OS=$(uname -s)"
      register: system_info
      changed_when: false
      tags: always
    
    - name: Display playbook information
      ansible.builtin.debug:
        msg: |
          =====================================
          AIX Memory Management Playbook
          =====================================
          Version: {{ playbook_version }}
          Target Hosts: {{ target_hosts | default('aix') }}
          AAP Job Template: {{ aap_job_template }}
          AAP Job ID: {{ aap_job_id }}
          AAP User: {{ aap_user }}
          Change Reason: {{ memory_change_reason }}
          Change Ticket: {{ memory_change_ticket }}
          HMC Host: {{ hmc_host }}
          =====================================
      tags: always
    
    - name: Validate target hosts
      ansible.builtin.fail:
        msg: "No valid AIX hosts found in inventory"
      when: "'OS=AIX' not in system_info.stdout"
      tags: always
    
    - name: Set memory threshold if provided
      ansible.builtin.set_fact:
        memory_threshold: "{{ memory_threshold_override }}"
      when: memory_threshold_override is defined
      tags: always
    
    - name: Set memory increment if provided
      ansible.builtin.set_fact:
        memory_increment_mb: "{{ memory_increment_override }}"
      when: memory_increment_override is defined
      tags: always
    
    - name: Validate HMC connectivity
      ansible.builtin.wait_for:
        host: "{{ hmc_host }}"
        port: 22
        timeout: 10
      delegate_to: localhost
      when: 
        - hmc_host is defined
        - hmc_host != ''
        - memory_auto_scaling_enabled | default(false) | bool
      failed_when: false
      tags: always

  roles:
    - role: memory_management
      tags:
        - memory
        - monitoring
        - auto_scaling
        - hmc
        - paging
  
  post_tasks:
    - name: Generate summary report
      ansible.builtin.debug:
        msg: |
          =====================================
          Memory Management Summary
          =====================================
          Host: {{ system_info.stdout_lines | select('match', '^HOSTNAME=') | first | regex_replace('HOSTNAME=', '') | default('unknown') }}
          Execution Time: {{ ansible_date_time.iso8601 if ansible_date_time is defined else 'N/A' }}
          Paging Threshold: {{ memory_threshold | default(10) }}%
          Memory Increment: {{ memory_increment_mb | default(512) }}MB
          Auto-scaling Enabled: {{ memory_auto_scaling_enabled | default(false) }}
          HMC Integration: {{ hmc_host | default('N/A') }}
          Status: Completed successfully
          =====================================
      tags: always