---
# tasks file for cloud_pvc
- name: Set cloud provider fact
  set_fact:
    selected_cloud: "{{ cloud_provider | lower }}"

- name: Provision AWS EBS Volume (example)
  when: selected_cloud == 'aws'
  amazon.aws.ec2_vol:
    name: "{{ pvc_name }}"
    size: "{{ size | regex_replace('Gi','') }}"
    region: "{{ region }}"
    state: present
  register: aws_pvc_result

- name: Provision Azure Disk (example)
  when: selected_cloud == 'azure'
  azure.azcollection.azure_managed_disk:
    resource_group: "{{ resource_group }}"
    name: "{{ pvc_name }}"
    size_gb: "{{ size | regex_replace('Gi','') }}"
    location: "{{ region }}"
    state: present
  register: azure_pvc_result

- name: Provision GCP Persistent Disk (example)
  when: selected_cloud == 'gcp'
  google.cloud.gcp_compute_disk:
    name: "{{ pvc_name }}"
    size_gb: "{{ size | regex_replace('Gi','') }}"
    zone: "{{ region }}"
    project: "{{ gcp_project }}"
    state: present
  register: gcp_pvc_result

- name: Show result
  debug:
    msg: |
      {% if selected_cloud == 'aws' %}
        AWS EBS Volume: {{ aws_pvc_result }}
      {% elif selected_cloud == 'azure' %}
        Azure Disk: {{ azure_pvc_result }}
      {% elif selected_cloud == 'gcp' %}
        GCP Persistent Disk: {{ gcp_pvc_result }}
      {% else %}
        No valid cloud provider selected.
      {% endif %}
