---
# Basic Fortinet Connection Test

- name: Basic Connection Test
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  
  tasks:
    - name: Get system global configuration
      fortinet.fortios.fortios_configuration_fact:
        vdom: "{{ vdom | default('root') }}"
        selector: 'system_global'
      register: config_result
      
    - name: Show connection status
      debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "Connection: {{ 'SUCCESS' if config_result is succeeded else 'FAILED' }}"
          - "{% if config_result is succeeded %}"
          - "Hostname: {{ config_result.meta.results.hostname | default('Not set') }}"
          - "{% endif %}"