---
# Basic Fortinet Connection Test
# Tests connectivity and authentication step by step

- name: Test Connection to Fortinet
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  
  tasks:
    - name: Show device info we're testing
      debug:
        msg:
          - "Testing connection to:"
          - "Hostname: {{ inventory_hostname }}"
          - "IP Address: {{ ansible_host | default('Not set in inventory') }}"
          - "User: {{ ansible_user }}"
          
    - name: Test network connectivity to device
      wait_for:
        host: "{{ ansible_host | default(inventory_hostname) }}"
        port: 443
        timeout: 10
      delegate_to: localhost
      connection: local
      register: connectivity
      ignore_errors: yes
      
    - name: Network test result
      debug:
        msg: "Network connectivity: {{ 'SUCCESS - Port 443 is reachable' if connectivity is succeeded else 'FAILED - Cannot reach port 443' }}"
        
    - name: Test authentication (if network is OK)
      fortinet.fortios.fortios_system_global:
        vdom: "{{ vdom | default('root') }}"
      check_mode: yes
      register: auth_result
      ignore_errors: yes
      when: connectivity is succeeded
      
    - name: Authentication result
      debug:
        msg: "Authentication: {{ 'SUCCESS - Credentials work' if auth_result is succeeded else 'FAILED - Check username/password' }}"
      when: connectivity is succeeded
      
    - name: Overall result
      debug:
        msg:
          - "================================"
          - "FINAL RESULT"
          - "================================"
          - "Network: {{ 'PASS' if connectivity is succeeded else 'FAIL' }}"
          - "Auth: {{ 'PASS' if auth_result is succeeded else 'FAIL' if connectivity is succeeded else 'NOT TESTED' }}"
          - "Status: {{ 'READY TO USE' if (connectivity is succeeded and auth_result is succeeded) else 'NEEDS FIXING' }}"
          
    - name: Troubleshooting info
      debug:
        msg:
          - "If network failed:"
          - "- Check ansible_host is correct in inventory"
          - "- Verify device is powered on and reachable"
          - "- Check firewall rules allow port 443"
          - ""
          - "If auth failed:"
          - "- Verify username/password in AAP credential"
          - "- Check device allows admin access via HTTPS"
          - "- Verify VDOM name is correct"
      when: connectivity is failed or (auth_result is defined and auth_result is failed)