---
- name: Check IKE Phase 1 Status
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  vars:
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    vdom: "{{ vdom | default('root') }}"
    vpn_name: "{{ vpn_name | default('vpn1') }}"
  tasks:
    - name: Get IKE Phase 1 status
      fortinet.fortios.fortios_monitor_fact:
        vdom: "{{ vdom }}"
        access_token: "{{ ansible_password | default(fortinet_api_token) }}"
        selector: 'vpn_ipsec'
      register: ike_phase1
    - name: Extract VPN status and set workflow facts
      set_fact:
        vpn_found: >-
          {{ (ike_phase1.meta.results | default([]) | selectattr('name', 'search', vpn_name) | list | length > 0) }}
        vpn_status: >-
          {%- set phase1_list = (ike_phase1.meta.results | default([]) | selectattr('name', 'search', vpn_name) | list) -%}
          {%- if phase1_list -%}
            {%- set phase1 = phase1_list[0] -%}
            {{- phase1.proxyid[0].status if phase1.proxyid and phase1.proxyid|length > 0 else 'unknown' -}}
          {%- else -%}
            not_found
          {%- endif -%}
        vpn_is_up: >-
          {%- set phase1_list = (ike_phase1.meta.results | default([]) | selectattr('name', 'search', vpn_name) | list) -%}
          {%- if phase1_list -%}
            {%- set phase1 = phase1_list[0] -%}
            {%- set status = phase1.proxyid[0].status if phase1.proxyid and phase1.proxyid|length > 0 else 'unknown' -%}
            {{- (status == 'up') | bool -}}
          {%- else -%}
            {{- false -}}
          {%- endif -%}
        vpn_details: "{{ ike_phase1.meta.results | selectattr('name', 'search', vpn_name) | list | first | default({}) }}"

    - name: Show VPN status results
      debug:
        msg:
          - "=============================="
          - "VPN {{ vpn_name }} Status Check"
          - "=============================="
          - "VPN Found: {{ vpn_found }}"
          - "VPN Status: {{ vpn_status | upper }}"
          - "VPN Is Up: {{ vpn_is_up }}"
          - "Workflow Result: {{ 'SUCCESS' if vpn_is_up else 'FAILED' }}"
          - ""
          - "VPN Details: {{ vpn_details }}"

    - name: Fail task if VPN is down (for workflow control)
      fail:
        msg: "VPN {{ vpn_name }} is {{ vpn_status | upper }} - Workflow failed"
      when: vpn_found and (vpn_status | trim) != 'up'

    - name: Fail task if VPN not found
      fail:
        msg: "VPN {{ vpn_name }} not found in FortiGate configuration"
      when: not vpn_found
