---
- name: Check VPN Phase 2 Status
  hosts: "{{ fortinet_hosts }}"
  gather_facts: no
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_network_os: fortios
    vdom: "{{ vdom | default('root') }}"
    vpn_name: "{{ vpn_name | default('vpn1') }}"
  tasks:
    - name: Get VPN Phase 2 status
      fortinet.fortios.fortios_monitor_fact:
        vdom: "{{ vdom }}"
        selector: 'vpn_ipsec_stats_crypto'
      register: vpn_phase2
    - name: Show status for specific VPN
      debug:
        msg: >
          {% set phase2 = (vpn_phase2.meta.results | selectattr('name', 'search', vpn_name) | list) %}
          {% if phase2 and phase2[0]['status'] == 'up' %}
            VPN {{ vpn_name }} Phase 2 is up
          {% elif phase2 %}
            VPN {{ vpn_name }} Phase 2 is down
          {% else %}
            VPN {{ vpn_name }} Phase 2 not found
          {% endif %}
