---
- name: Check IKE Phase 1 Status
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  vars:
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    vdom: "{{ vdom | default('root') }}"
    vpn_name: "{{ vpn_name | default('vpn1') }}"
  tasks:
    - name: Get IKE Phase 1 status
      fortinet.fortios.fortios_monitor_fact:
        vdom: "{{ vdom }}"
        access_token: "{{ ansible_password | default(fortinet_api_token) }}"
        selector: 'vpn_ipsec'
      register: ike_phase1
    - name: Show status for specific VPN
      debug:
        msg: >
          {% set phase1_list = (ike_phase1.meta.results | default([]) | selectattr('name', 'search', vpn_name) | list) %}
          {% if phase1_list %}
            {% set phase1 = phase1_list[0] %}
            {% set proxy_status = phase1.proxyid[0].status if phase1.proxyid and phase1.proxyid|length > 0 else 'unknown' %}
            VPN {{ vpn_name }} Phase 1 Status: {{ proxy_status | upper }}
            - VPN Name: {{ phase1.name }}
            - Remote Gateway: {{ phase1.rgwy | default('Unknown') }}
            - Connection Count: {{ phase1.connection_count | default(0) }}
            - Incoming Bytes: {{ phase1.incoming_bytes | default(0) }}
            - Outgoing Bytes: {{ phase1.outgoing_bytes | default(0) }}
          {% else %}
            VPN {{ vpn_name }} not found in FortiGate configuration
          {% endif %}
