---
- name: Check IKE Phase 1 Status
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  vars:
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    vdom: "{{ vdom | default('root') }}"
    vpn_name: "{{ vpn_name | default('vpn1') }}"
  tasks:
    - name: Get IKE Phase 1 status
      fortinet.fortios.fortios_monitor_fact:
        vdom: "{{ vdom }}"
        access_token: "{{ ansible_password | default(fortinet_api_token) }}"
        selector: 'vpn_ipsec'
      register: ike_phase1
    - name: Show raw VPN data for debugging
      debug:
        msg: "Raw VPN data: {{ ike_phase1.meta.results | default('No results') }}"
        
    - name: Show status for specific VPN
      debug:
        msg: >
          {% set phase1_list = (ike_phase1.meta.results | default([]) | selectattr('name', 'search', vpn_name) | list) %}
          {% if phase1_list %}
            {% set phase1 = phase1_list[0] %}
            VPN {{ vpn_name }} found - Name: {{ phase1.name | default('Unknown') }}, 
            State: {{ phase1.state | default('Unknown') }},
            Proxyid: {{ phase1.proxyid | default('N/A') }}
          {% else %}
            VPN {{ vpn_name }} not found in results
          {% endif %}
