---
- name: Flush VPN Phase 2 Tunnel
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  vars:
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    vpn_name: "{{ vpn_name | default('vpn1') }}"
    vdom: "{{ vdom | default('root') }}"
  tasks:
    - name: Get VPN Phase 2 tunnels for the VPN
      fortinet.fortios.fortios_monitor_fact:
        vdom: "{{ vdom }}"
        access_token: "{{ ansible_password | default(fortinet_api_token) }}"
        selector: 'vpn_ipsec_stats_crypto'
      register: vpn_phase2

    - name: Set list of phase2 tunnels related to the VPN
      set_fact:
        phase2_names: >-
          {{ vpn_phase2.meta.results | selectattr('name', 'search', vpn_name) | map(attribute='name') | list | unique }}

    - name: Flush all Phase 2 tunnels for the VPN
      fortinet.fortios.fortios_vpn_ipsec_phase2_interface:
        state: "absent"
        vdom: "{{ vdom }}"
        access_token: "{{ ansible_password | default(fortinet_api_token) }}"
        name: "{{ item }}"
      loop: "{{ phase2_names }}"
      register: flush_result

    - name: Show flush result
      debug:
        var: flush_result
