---
- name: Flush Tunnel 1
  hosts: "{{ fortinet_hosts }}"
  gather_facts: no
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_network_os: fortios
    tunnel_name: "{{ tunnel_name | default('tunnel1') }}"
    vdom: "{{ vdom | default('root') }}"
  tasks:
    - name: Flush tunnel 1
      fortinet.fortios.fortios_vpn_ipsec_phase2_interface:
        state: "absent"
        vdom: "{{ vdom }}"
        name: "{{ tunnel_name }}"
      register: flush_tunnel1_result
    - name: Show flush result
      debug:
        var: flush_tunnel1_result
