---
# Check AAP Inventory Configuration
# Helps diagnose connection issues

- name: Check Inventory Configuration
  hosts: "{{ target_hosts }}"
  gather_facts: yes
  connection: httpapi
  become: no
  
  tasks:
    - name: Display all inventory variables
      debug:
        msg:
          - "=== INVENTORY DIAGNOSTICS ==="
          - "Inventory hostname: {{ inventory_hostname }}"
          - "ansible_host: {{ ansible_host | default('NOT SET') }}"
          - "ansible_connection: {{ ansible_connection | default('NOT SET') }}"
          - "ansible_network_os: {{ ansible_network_os | default('NOT SET') }}"
          - "ansible_httpapi_port: {{ ansible_httpapi_port | default('NOT SET') }}"
          - "ansible_httpapi_use_ssl: {{ ansible_httpapi_use_ssl | default('NOT SET') }}"
          - "ansible_user: {{ ansible_user | default('NOT SET') }}"
          - "Groups: {{ group_names }}"
          - ""
          - "=== NETWORK TEST ==="
          
    - name: Test network connectivity with correct variables
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ansible_httpapi_port | default(443) }}"
        timeout: 10
      delegate_to: localhost
      connection: local
      register: network_test
      ignore_errors: yes
      when: ansible_host is defined
      
    - name: Show network test result
      debug:
        msg: 
          - "Network test to {{ ansible_host }}:{{ ansible_httpapi_port | default(443) }}"
          - "Result: {{ 'SUCCESS' if network_test is succeeded else 'FAILED' }}"
          - "Error: {{ network_test.msg | default('N/A') }}"
      when: ansible_host is defined
      
    - name: Warning if ansible_host not set
      debug:
        msg:
          - "WARNING: ansible_host is not set in inventory!"
          - "This is likely why the connection test failed."
          - "Please add ansible_host to your inventory configuration."
      when: ansible_host is not defined