---
- name: Run Diagnostic on Fortinet VA
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  vars:
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    diag_command: "{{ diagnostic_command | default('diagnose vpn ike gateway list') }}"
    vdom: "{{ vdom | default('root') }}"
  tasks:
    - name: Run diagnostic command
      fortinet.fortios.fortios_monitor_fact:
        vdom: "{{ vdom }}"
        selector: 'system_status'
        access_token: "{{ ansible_password | default(fortinet_api_token) }}"
      register: diag_result
    - name: Show diagnostic result
      debug:
        var: diag_result
