---
- name: Run Diagnostic on Fortinet VA
  hosts: "{{ fortinet_hosts }}"
  gather_facts: no
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_network_os: fortios
    diag_command: "{{ diagnostic_command | default('diagnose vpn ike gateway list') }}"
    vdom: "{{ vdom | default('root') }}"
  tasks:
    - name: Run diagnostic command
      fortinet.fortios.fortios_monitor_fact:
        vdom: "{{ vdom }}"
        selector: 'system_status'
      register: diag_result
    - name: Show diagnostic result
      debug:
        var: diag_result
