---
# Working Fortinet Connection Test
# Uses the most basic approach that actually works

- name: Simple Fortinet Connection Test
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  vars:
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  
  tasks:
    - name: Test connection using fortios_command
      fortinet.fortios.fortios_command:
        vdom: "{{ vdom | default('root') }}"
        commands:
          - get system status
      register: command_result
      ignore_errors: yes
      
    - name: Show basic result
      debug:
        msg:
          - "==============================="
          - "Fortinet Connection Test"
          - "==============================="
          - "Device: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "Status: {{ 'CONNECTED' if command_result is succeeded else 'FAILED' }}"
          
    - name: Show success details
      debug:
        msg:
          - "✅ Connection successful!"
          - "✅ Authentication working"
          - "✅ Device responded to command"
      when: command_result is succeeded
      
    - name: Show failure details  
      debug:
        msg:
          - "❌ Connection failed"
          - "Error: {{ command_result.msg | default('Unknown error') }}"
          - ""
          - "Check your AAP configuration:"
          - "- Inventory host has correct ansible_host"
          - "- Machine credential has correct username/password"
          - "- Device allows HTTPS admin access on port 443"
      when: command_result is failed