---
# Test Connection to Fortinet Device
# Use this playbook to verify credentials and connectivity before running other playbooks
# Required variables: target_hosts (device/group), vdom (default: root)

- name: Test Fortinet Connection
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  
  tasks:
    - name: Test connection by getting system global config
      fortinet.fortios.fortios_system_global:
        vdom: "{{ vdom | default('root') }}"
        state: "present"
      check_mode: yes
      register: connection_test
      ignore_errors: yes
      
    - name: Show connection result
      debug:
        msg:
          - "==============================="
          - "Fortinet Connection Test"
          - "==============================="
          - "Device: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "VDOM: {{ vdom | default('root') }}"
          - ""
          - "Status: {{ 'CONNECTION SUCCESS!' if connection_test is not failed else 'CONNECTION FAILED!' }}"
          
    - name: Show success details
      debug:
        msg:
          - "✅ Successfully authenticated to FortiGate"
          - "✅ API connection working"
          - "✅ Credentials are valid"
      when: connection_test is not failed
      
    - name: Show failure details
      debug:
        msg:
          - "❌ Connection failed"
          - "Error: {{ connection_test.msg | default('Unknown error') }}"
          - ""
          - "Check:"
          - "- Device IP/hostname is correct"
          - "- Username/password in AAP credential"
          - "- Device allows HTTPS admin access"
          - "- Port 443 is accessible"
      when: connection_test is failed