---
# Test Connection to Fortinet Device
# Simple connection test that actually works

- name: Test Fortinet Connection
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  
  tasks:
    - name: Test connection by reading current hostname
      fortinet.fortios.fortios_system_global:
        vdom: "{{ vdom | default('root') }}"
        system_global:
          hostname: "{{ inventory_hostname }}"
      check_mode: yes
      register: connection_test
      ignore_errors: yes
      
    - name: Alternative test - try getting facts
      fortinet.fortios.fortios_facts:
        vdom: "{{ vdom | default('root') }}"
        gather_subset:
          - fact: 'system_status'
      register: facts_test
      ignore_errors: yes
      when: connection_test is failed
      
    - name: Final connection status
      debug:
        msg:
          - "==============================="
          - "Fortinet Connection Test"
          - "==============================="
          - "Device: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "VDOM: {{ vdom | default('root') }}"
          - ""
          - "Result: {{ 'SUCCESS - Connected!' if (connection_test is succeeded or facts_test is succeeded) else 'FAILED - Cannot Connect' }}"
          
    - name: Show success message
      debug:
        msg:
          - "✅ Connection established"
          - "✅ Authentication successful"
          - "✅ Ready to run Fortinet playbooks"
      when: connection_test is succeeded or facts_test is succeeded
      
    - name: Show detailed error
      debug:
        msg:
          - "❌ Connection failed"
          - "First attempt error: {{ connection_test.msg | default('N/A') }}"
          - "{% if facts_test is defined %}Second attempt error: {{ facts_test.msg | default('N/A') }}{% endif %}"
          - ""
          - "Troubleshooting:"
          - "1. Verify device IP: {{ ansible_host | default('not set') }}"
          - "2. Check AAP credential username/password"
          - "3. Ensure FortiGate allows HTTPS admin access"
          - "4. Verify port 443 is accessible from AAP"
      when: connection_test is failed and (facts_test is not defined or facts_test is failed)