---
# Test Connection to Fortinet Device
# Use this playbook to verify credentials and connectivity before running other playbooks
# Required variables: target_hosts (device/group), vdom (default: root)

- name: Test Fortinet Authentication
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  
  tasks:
    - name: Test authentication by getting system interface
      fortinet.fortios.fortios_monitor:
        vdom: "{{ vdom | default('root') }}"
        selector: 'system_interface'
      register: auth_test
      ignore_errors: yes
      
    - name: Show connection status
      debug:
        msg:
          - "==============================="
          - "Fortinet Connection Test"
          - "==============================="
          - "Device: {{ inventory_hostname }}"
          - "User: {{ ansible_user }}"
          - "VDOM: {{ vdom | default('root') }}"
          - ""
          - "Result: {{ 'CONNECTION SUCCESSFUL!' if auth_test is succeeded else 'CONNECTION FAILED!' }}"
          
    - name: Show error details if failed
      debug:
        msg: "Error: {{ auth_test.msg | default('Unknown error') }}"
      when: auth_test is failed
      
    - name: Show success details
      debug:
        msg: 
          - "Response Code: {{ auth_test.meta.response_code | default('N/A') }}"
          - "Successfully connected to Fortinet device"
      when: auth_test is succeeded