---
# FortiGate Token Authentication Test
# Tests connection using API token instead of username/password

- name: Test FortiGate Token Authentication
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  vars:
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  
  tasks:
    - name: Test token authentication
      fortinet.fortios.fortios_system_global:
        vdom: "{{ vdom | default('root') }}"
        access_token: "{{ fortinet_api_token }}"
      check_mode: yes
      register: token_test
      ignore_errors: yes
      
    - name: Show connection result
      debug:
        msg:
          - "==============================="
          - "FortiGate Token Authentication Test"
          - "==============================="
          - "Device: {{ inventory_hostname }}"
          - "IP: {{ ansible_host | default('Not set') }}"
          - "Port: {{ ansible_httpapi_port | default(443) }}"
          - "VDOM: {{ vdom | default('root') }}"
          - ""
          - "Token Auth: {{ 'SUCCESS!' if token_test is succeeded else 'FAILED!' }}"
          
    - name: Show success details
      debug:
        msg:
          - "✅ Token authentication working"
          - "✅ API access granted"
          - "✅ Ready for automation"
      when: token_test is succeeded
      
    - name: Show failure details
      debug:
        msg:
          - "❌ Token authentication failed"
          - "Error: {{ token_test.msg | default('Unknown error') }}"
          - ""
          - "Check:"
          - "- API token is valid and not expired"
          - "- Token has correct permissions"
          - "- HTTPS admin access is enabled on device"
          - "- Correct port ({{ ansible_httpapi_port | default(443) }}) is configured"
      when: token_test is failed