---
# Ultra Simple Fortinet Connection Test
# Just tests if we can authenticate and access the device

- name: Ultra Simple Connection Test
  hosts: "{{ target_hosts }}"
  gather_facts: no
  connection: httpapi
  become: no
  
  tasks:
    - name: Test authentication by accessing system global
      fortinet.fortios.fortios_system_global:
        vdom: "{{ vdom | default('root') }}"
      check_mode: yes
      register: auth_result
      ignore_errors: yes
      
    - name: Connection result
      debug:
        msg:
          - "Device: {{ inventory_hostname }}"
          - "Result: {{ 'SUCCESS' if auth_result is not failed else 'FAILED' }}"
          
    - name: Success message
      debug:
        msg: "✅ Authentication successful - device is reachable!"
      when: auth_result is not failed
      
    - name: Error message
      debug:
        msg: "❌ Failed: {{ auth_result.msg }}"
      when: auth_result is failed