---
- name: Verify Application over TCP/IP
  hosts: "{{ fortinet_hosts }}"
  gather_facts: no
  vars:
    app_host: "{{ app_host | default('app.example.com') }}"
    app_port: "{{ app_port | default('80') }}"
  tasks:
    - name: Check TCP port
      ansible.builtin.wait_for:
        host: "{{ app_host }}"
        port: "{{ app_port }}"
        state: started
        timeout: 10
      register: tcp_check
      delegate_to: localhost
    - name: Show TCP check result
      debug:
        var: tcp_check
