---
- name: Verify Application over TCP/IP
  hosts: localhost
  gather_facts: no
  become: no
  vars:
    target_host: "{{ target_host | mandatory }}"
    target_port: "{{ target_port | mandatory }}"
    check_timeout: "{{ check_timeout | default(10) }}"
  tasks:
    - name: Check TCP port accessibility from execution environment
      ansible.builtin.wait_for:
        host: "{{ target_host }}"
        port: "{{ target_port }}"
        state: started
        timeout: "{{ check_timeout }}"
        msg: "Port {{ target_port }} on {{ target_host }} is not accessible"
      register: tcp_check
      failed_when: false

    - name: Report success if port is accessible
      ansible.builtin.debug:
        msg: "SUCCESS: Port {{ target_port }} on {{ target_host }} is accessible"
      when: tcp_check.exception is not defined

    - name: Fail if port is not accessible
      ansible.builtin.fail:
        msg: "FAILED: Port {{ target_port }} on {{ target_host }} is not accessible after {{ check_timeout }} seconds"
      when: tcp_check.exception is defined
