---
# AAP 2.5 Execution Environment Specification for OS Patching
# This file defines the execution environment requirements for the OS patching playbook

version: 3

# Base image with Python and Ansible runtime
images:
  base_image:
    name: 'quay.io/ansible/ansible-runner:2.13'

# Dependencies for execution environment
dependencies:
  # Ansible Collections required for OS patching
  galaxy: requirements.yml
  
  # Python packages needed for collections
  python: |
    requests>=2.25.0
    pywinrm>=0.4.3
    jinja2>=3.0.0
    packaging>=21.0
    setuptools>=50.0

  # System packages for Linux/Windows management
  system: |
    openssh-clients
    python3-pip
    git
    rsync

# Additional configuration for AAP 2.5
additional_build_steps:
  prepend_base: |
    RUN pip3 install --upgrade pip
    
  append_final: |
    # Ensure proper permissions for Ansible
    RUN chmod +x /usr/local/bin/*
    
    # Create directories for logging
    RUN mkdir -p /tmp/ansible-patching-logs
    
    # Set timezone for consistent logging
    RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime

# Build arguments for customization
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--pre"
  
# Environment variables for execution
environment_variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"
  ANSIBLE_INVENTORY_UNPARSED_FAILED: "True"
  ANSIBLE_PARAMIKO_RECORD_HOST_KEYS: "False"
