---
# AAP 2.5 Execution Environment Compatible OS Patching Playbook
#
# This playbook is designed for Ansible Automation Platform 2.5:
# - Execution Environment compatibility
# - AAP Inventory integration
# - AAP Credential management
# - Web console survey integration
#
# Prerequisites:
# - AAP 2.5 with execution environment
# - AAP inventory with proper host groups
# - AAP credentials for target systems
# - Survey configuration (patching_survey.json)
#
- name: OS Patching
  hosts: "{{ patch_target | default('all') }}"
  gather_facts: true
  become: true

  # Best Practice: Use AAP job template settings for concurrent jobs
  # and execution environment resource allocation

  vars:
    # Survey variables with safe defaults
    allow_reboot: "{{ allow_reboot | default(false) | bool }}"
    win_update_categories: "{{ win_update_categories | default(['SecurityUpdates', 'CriticalUpdates']) }}"
    linux_exclude_packages: "{{ linux_exclude_packages | default('') }}"
    pre_patch_snapshot: "{{ pre_patch_snapshot | default(false) | bool }}"
    notification_email: "{{ notification_email | default('') }}"
    maintenance_window_hours: "{{ maintenance_window_hours | default(2) | int }}"

    # AAP execution environment variables
    aap_job_id: "{{ tower_job_id | default(awx_job_id) | default('N/A') }}"
    aap_job_template: "{{ tower_job_template_name | default(awx_job_template_name) | default('OS Patching') }}"
    aap_user: "{{ tower_user_name | default(awx_user_name) | default(ansible_user) }}"

  pre_tasks:
    - name: Display AAP execution environment information
      ansible.builtin.debug:
        msg:
          - "=== AAP 2.5 Execution Environment Patching ==="
          - "Job Template: {{ aap_job_template }}"
          - "Job ID: {{ aap_job_id }}"
          - "Execution Environment: {{ ansible_runner_job_uuid | default('default-ee') }}"
          - "Target Pattern: {{ patch_target | default('all') }}"
          - "Allow Reboot: {{ allow_reboot }}"
          - "Maintenance Window: {{ maintenance_window_hours }} hours"
          - "Started by: {{ aap_user }}"
      run_once: true
      delegate_to: localhost
      tags:
        - always
        - info

    - name: Validate required AAP variables
      ansible.builtin.assert:
        that:
          - inventory_hostname is defined
          - ansible_os_family is defined
        fail_msg: "Missing required AAP inventory or fact variables"
        success_msg: "AAP inventory validation successful"
      tags:
        - always
        - validation

  roles:
    - role: linux_patching
      when: ansible_os_family in ["RedHat", "Debian"]
      tags:
        - linux
        - patch
    - role: windows_patching
      when: ansible_os_family == "Windows"
      tags:
        - windows
        - patch

  post_tasks:
    - name: Log patching completion to execution environment
      ansible.builtin.debug:
        msg:
          - "Patching completed for {{ inventory_hostname }}"
          - "OS Family: {{ ansible_os_family }}"
          - "Reboot Required: {{ patching_reboot_required | default(false) }}"
          - "AAP Job ID: {{ aap_job_id }}"
      tags:
        - always
        - summary

    - name: Reboot system if required and allowed
      block:
        - name: Reboot Linux system
          ansible.builtin.reboot:
            reboot_timeout: 600
            test_command: uptime
          when: ansible_os_family != "Windows"
          tags:
            - reboot
            - linux

        - name: Reboot Windows system
          ansible.windows.win_reboot:
            reboot_timeout: 600
          when: ansible_os_family == "Windows"
          tags:
            - reboot
            - windows

        - name: Log reboot completion
          ansible.builtin.debug:
            msg: "System {{ inventory_hostname }} successfully rebooted"
          tags:
            - reboot
      when: 
        - patching_reboot_required | default(false)
        - allow_reboot
      tags:
        - reboot

    - name: Notify about pending reboot
      ansible.builtin.debug:
        msg: "ATTENTION: {{ inventory_hostname }} requires reboot but automatic reboot is disabled"
      when: 
        - patching_reboot_required | default(false)
        - not allow_reboot
      tags:
        - reboot
        - warning

- name: Patching Summary and Notification
  hosts: localhost
  gather_facts: false
  connection: local
  become: false

  vars:
    # Access variables from patching play
    aap_job_id: "{{ tower_job_id | default(awx_job_id) | default('N/A') }}"
    notification_email: "{{ notification_email | default('') }}"

  tasks:
    - name: Generate AAP execution environment summary
      ansible.builtin.set_fact:
        patching_summary:
          job_id: "{{ aap_job_id }}"
          execution_environment: "{{ ansible_runner_job_uuid | default('default-ee') }}"
          total_hosts: "{{ ansible_play_hosts_all | length }}"
          completion_time: "{{ ansible_date_time.iso8601 }}"
      tags:
        - always
        - summary
    - name: Display patching summary
      ansible.builtin.debug:
        msg:
          - "=== AAP 2.5 Execution Environment Patching Summary ==="
          - "Job ID: {{ patching_summary.job_id }}"
          - "Execution Environment: {{ patching_summary.execution_environment }}"
          - "Total Hosts: {{ patching_summary.total_hosts }}"
          - "Completion Time: {{ patching_summary.completion_time }}"
      when: notification_email == ''
      tags:
        - always
        - summary
    - name: Send completion notification via AAP
      community.general.mail:
        to: "{{ notification_email }}"
        subject: "AAP 2.5 Patching Job {{ patching_summary.job_id }} - Completed"
        body: |
          Ansible Automation Platform 2.5 Patching Summary
          
          Job ID: {{ patching_summary.job_id }}
          Execution Environment: {{ patching_summary.execution_environment }}
          Total Hosts Processed: {{ patching_summary.total_hosts }}
          Completion Time: {{ patching_summary.completion_time }}
          
          View detailed results in the AAP web console.
      when: 
        - notification_email != ''
        - notification_email is defined
      ignore_errors: true
      tags:
        - always
        - notification
