---
# tasks file for cloud_security
- name: Set cloud provider fact
  set_fact:
    selected_cloud: "{{ cloud_provider | lower }}"

- name: Setup AWS Security Group
  when: selected_cloud == 'aws'
  amazon.aws.ec2_group:
    name: "{{ security_group_name }}"
    description: "Managed by Ansible"
    region: "{{ region }}"
    rules: "{{ security_rules | default([]) }}"
    state: present
  register: aws_sg_result

- name: Setup Azure Security Group
  when: selected_cloud == 'azure'
  azure.azcollection.azure_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ security_group_name }}"
    location: "{{ region }}"
    security_rules: "{{ security_rules | default([]) }}"
    state: present
  register: azure_sg_result

- name: Setup GCP Firewall Rule
  when: selected_cloud == 'gcp'
  google.cloud.gcp_compute_firewall:
    name: "{{ security_group_name }}"
    network: default
    allowed: "{{ security_rules | default([]) }}"
    project: "{{ gcp_project }}"
    state: present
  register: gcp_sg_result

- name: Show result
  debug:
    msg: |
      {% if selected_cloud == 'aws' %}
        AWS Security Group: {{ aws_sg_result }}
      {% elif selected_cloud == 'azure' %}
        Azure Security Group: {{ azure_sg_result }}
      {% elif selected_cloud == 'gcp' %}
        GCP Firewall Rule: {{ gcp_sg_result }}
      {% else %}
        No valid cloud provider selected.
      {% endif %}
