---
# Simple Fortinet Execution Environment for AAP 2.5
version: 3

images:
  base_image:
    name: 'docker.io/python:3.9-slim'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  python_interpreter:
    python_path: "/usr/local/bin/python3"

additional_build_steps:
  prepend_base:
    - RUN apt-get update && apt-get install -y gcc git && rm -rf /var/lib/apt/lists/*
    - RUN pip install --upgrade pip ansible-core>=2.15.0 ansible-runner>=2.3.0
    - RUN ln -sf /usr/local/bin/python3 /usr/bin/python3
  
  append_final:
    - RUN ansible-galaxy collection list
    - RUN pip list | grep -E "(ansible|fortiosapi)"